
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.123.103:9092,192.168.123.104:9092,192.168.123.105:9092
      DYNAMIC_CONFIG_ENABLED: true

